### ISSUE TITLE
Ejercicios_maritza_carla_anais_maricruz

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-2-ejercicios-2363#2]
[Maritza_Carla_Maricruz_Anais.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-ejercicios-2363/files/12556281/Maritza_Carla_Maricruz_Anais.pdf)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 22%
Figuras, ilutraciones y fotografias 20%
Resultados y conclusiones 20%
Calificacion final 17/20
Calificado por el equipo de Elisa Sanchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
